### ISSUE TITLE
Question: Have you had any success with pyDMNrules on numba or pypy?

### ISSUE THREAD

**Issue by aria-blackford** [russellmcdonell/pyDMNrules#12]
I have a use case where performance is very important. I'll be running the same model millions of times sequentially. Have you had success compiling with numba or pypy? I'm not particularly experienced with pypy but believe I'm using it appropriately, it hasn't had any impact at all on performance. ExampleHPV.xlsx for example takes around 4 seconds to run 500 times with or without pypy.

**Comment by russellmcdonell** [comment]
To be honest I have not tried. However pyDMNrules uses pySFeel which uses SLY. The whole thing is very heavily linguistic based, not scientific computational based. And in reality, pyDMNrules is intended to be a beginners introduction tool to DMN. There are high performance DMN implementations out there, such as OpenRules. O.K. - it's Java, not Python, but you can stand it up as an API service and just ignore the programming language difference.
