### ISSUE TITLE
Unexpected decision with double quotes

### ISSUE THREAD

**Issue by Airscripts** [russellmcdonell/pyDMNrules#5]
Hello Russell, 

We're using your pyDMNrules inside some of our projects.
I'm opening this issue because we have found out something that can be a bug.

The version that I'm using here is the 0.1.7.
And the problem is that if we check for rule number 5, for example, it will match the rule number 4.
No matter what you pass as input, it will match everytime the rule number 4.

Is there anything I need to know about double quoted strings?
I've checked the documentation and I haven't found out anything related.

Thank you so much for your time and this project, it is very helpful for our daily work.

![image](https://user-images.githubusercontent.com/43211620/162015162-58614fe2-575d-4821-b23a-f163bf4c2588.png)

**Comment by russellmcdonell** [comment]
The current version of pyDMNrules is 1.3.16 and the current version of pySFeel is 1.3.7
There have been quite a few bug fixes in the intervening releases. I've tried the attached workbook, as an attempt to replicate our issue, and I can't replicate it. So my recommendation would be to upgrade.
[NOTE: the latest version doesn't require a Glossary or a Decision worksheet - so this won't work with your older version]
[problema mezzo.xlsx](https://github.com/russellmcdonell/pyDMNrules/files/8439618/problema.mezzo.xlsx)

**Comment by Airscripts** [comment]
I've tried using pyDMNrules 1.3.16.

I can clearly see that I have DMN objects loaded but then, when asking for a decision I get the following error:
`'No rulesBook has been loaded'`

Do you have any clue for this? 
I've looked up the documentation but I couldn't find anything related.
Thank you in advance for your time.

**Comment by russellmcdonell** [comment]
Can you send me the Excel workbook? I realize that this will contain business confidential information, so you may have to modify it. However, when you do that you may 'move' the problem. So, as a starting point, I'd look at the status returned when you loaded the Excel workbook. That should tell you why the rules in the Excel workbook did not get loaded.

If you can't work it out from that, try disguise the business logic, making sure that you are getting the same error, when you try and load the workbook.

P.S. - I always follow status = pyDMNrule.load() with a check if 'errors' in status: ABORT.

**Comment by Airscripts** [comment]
Hi Russell, sorry for my late response.

This problem doesn't occur in other software that use a later version so it's related on how it's implemented on the one that loads the older version of pyDMNrules.

Thank you for your support, you can close the issue.

**Comment by russellmcdonell** [comment]
Thank you for your feedback and support.
