### ISSUE TITLE
Input Validity List

### ISSUE THREAD

**Issue by bocaguy** [russellmcdonell/pyDMNrules#7]
Is there a way to create a rule that basically equates to "is one of." If someone sends a file with an invalid (or missing) geographic state (as opposed sending to NY, PA, MS, CA) I can trap it without getting the error that the state does not match the input validity list? Thanks;

**Comment by bocaguy** [comment]
Found the fix (use "not")

**Comment by bocaguy** [comment]
Did not know the input validity list could be replaced by the variable itself (so it's in two contiguous columns) and then use a '-' in the last column so it cascades down to the unrecognized variable.

**Comment by russellmcdonell** [comment]
I believe this issue has been clarified.

**Comment by russellmcdonell** [comment]
I've done things with 'state' before. Check out AN-SNAP V4 grouper
(DMN).xlsx
<https://github.com/russellmcdonell/DecisionCentral/blob/main/DMNexamples/AN-SNAP%20V4%20grouper%20(DMN).xlsx>

So, in the Decision (list of Decision Tables to be run), I'd start with
validateState - a simple table with one input (the state) and one output
'valid'

U      state          ||valid
=|===========||====
1|NY,PA,MS,CA||true
2|        -              ||false

Then, in Decision, all subsequent rows test 'valid' == 'true', and hence
get skipped if the state is invalid.
On return from decide(), check 'valid' before checking anything else.

Russell McDonell
